### ISSUE TITLE
OOM error searching in a bigdata set having a really smal value set.

### ISSUE THREAD

**Issue by eurospy** [tjake/Solandra#10]
I've added 350k documents through lucandra in the same index,
every document had a type field where 3 possible values are possible.
type:internal (approx 130k documents)
type:external (approx 200k documents)
type:advertorial approx 20k documents)

since the type field does not need to be tokenized, I'm indexing with Store.YES,Index.NOT_ANALYZED
## so, when I try to do a search like "type:internal" it does work for a while but I get an exception like this after a few minutes:

10/04/28 14:40:34 INFO lucandra.IndexReader: docFreq() took: 16932ms
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
    at java.nio.ByteBuffer.wrap(ByteBuffer.java:350)
    at java.lang.StringCoding$StringDecoder.decode(StringCoding.java:137)
    at java.lang.StringCoding.decode(StringCoding.java:173)
    at java.lang.String.<init>(String.java:443)
    at java.lang.String.<init>(String.java:515)
    at lucandra.IndexReader.addDocument(IndexReader.java:375)
    at lucandra.LucandraTermEnum.getTermDocFreq(LucandraTermEnum.java:287)
    at lucandra.LucandraTermDocs.seek(LucandraTermDocs.java:106)
    at org.apache.lucene.index.IndexReader.termDocs(IndexReader.java:814)
    at org.apache.lucene.search.TermQuery$TermWeight.scorer(TermQuery.java:74)
    at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:205)
    at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:168)
    at org.apache.lucene.search.Searcher.search(Searcher.java:98)
    at org.apache.lucene.search.Searcher.search(Searcher.java:108)
##     at LucandraTest.main(LucandraTest.java:74)

and for instance if I do search for limiting some other fields and say, I get 1000 hits as result, with a query like "foo:bar\* AND blah:bla_" 
if I add the type in the query "foo:bar_ AND blah:bla\* AND type:internal" It takes a really long time and finally I get the same exception.

I'm basically using the same code in the bookmarks demo for indexing and searching the documents, so I didn't feel the need to post the sample code.

**Comment by tjake** [comment]
I'm working on a custom query filter for lucandra, in the meantime have you considered creating 3 indexes representing each of your types and search from the one you need rather than filtering from one big index?

**Comment by tjake** [comment]
This has been addressed as part of http://github.com/tjake/Lucandra/issues/closed#issue/16

Please see testLucandraFilter unit test for example.

**Comment by eurospy** [comment]
thanks for the update, I'm now getting the performance in filterin enumerations
