### ISSUE TITLE
java.io.IOException: invalid core 'website'

### ISSUE THREAD

**Issue by alfredas** [tjake/Solandra#109]
After importing data in the reuters example

http://localhost:8983/solandra/website/index.html 

returns Error 500:

java.io.IOException: invalid core 'website'

java.lang.RuntimeException: java.io.IOException: invalid core 'website'
    at org.apache.solr.core.SolandraCoreContainer.getCore(SolandraCoreContainer.java:104)
    at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:194)
    at solandra.SolandraDispatchFilter.doFilter(SolandraDispatchFilter.java:137)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: java.io.IOException: invalid core 'website'
    at org.apache.solr.core.SolandraCoreContainer.readSchema(SolandraCoreContainer.java:157)
    at org.apache.solr.core.SolandraCoreContainer.getCore(SolandraCoreContainer.java:100)
    ... 15 more

**Comment by ycoe** [comment]
I got the same exception,what's the matter?
why closed this issue?
fixed?

**Comment by tjake** [comment]
Hi,

The demo isn't hosted through solandra.  You need to open the index.html file through your browser's File->Open File menu option.

**Comment by ycoe** [comment]
thanks,it work!

**Comment by dansherpa** [comment]
Any suggestions for enjoying the Reuter's data load on a headless system (i.e. no GUI)?
