### ISSUE TITLE
Could not build Solandra (UNRESOLVED DEPENDENCIES)

### ISSUE THREAD

**Issue by fabio-cancio-sena** [tjake/Solandra#113]
SO: Windows 7 (64-bit)
C:\Temp\Solandra>java -version
java version "1.6.0_26"
Java(TM) SE Runtime Environment (build 1.6.0_26-b03)
Java HotSpot(TM) 64-Bit Server VM (build 20.1-b02, mixed mode)

C:\Temp\Solandra>ant -v
...
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   93  |   0   |   0   |   10  ||   83  |   0   |
        ---------------------------------------------------------------------
[ivy:retrieve] WARN:    ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve] WARN:    ::          UNRESOLVED DEPENDENCIES         ::
[ivy:retrieve] WARN:    ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve] WARN:    :: jline#jline;0.9.94: configuration not found in jline#jline;0.9.94: 'compile'. It was required from org.apache.cassandra#cassandra-all;0.8.1 compile
[ivy:retrieve] WARN:    :: javax.servlet#servlet-api;2.5: configuration not found in javax.servlet#servlet-api;2.5: 'compile'. It was required from org.apache.thrift#libthrift;0.6.1 compile
[ivy:retrieve] WARN:    ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve]  report for solandra#solandra;working@fabiosena-acer default produced in C:\Users\fabiosena.ivy2\cache\solandra-solandra-default.xml
[ivy:retrieve]  resolve done (4802ms resolve - 132ms download)
[ivy:retrieve]
[ivy:retrieve] :: problems summary ::
[ivy:retrieve] :::: WARNINGS
[ivy:retrieve]          ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve]          ::          UNRESOLVED DEPENDENCIES         ::
[ivy:retrieve]          ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve]          :: jline#jline;0.9.94: configuration not found in jline#jline;0.9.94: 'compile'. It was required from org.apache.cassandra#cassandra-all;0.8.1 compile
[ivy:retrieve]          :: javax.servlet#servlet-api;2.5: configuration not found in javax.servlet#servlet-api;2.5: 'compile'. It was required from org.apache.thrift#libthrift;0.6.1 compile
[ivy:retrieve]          ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve]
[ivy:retrieve]
[ivy:retrieve] :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS

BUILD FAILED
C:\Temp\Solandra\build.xml:102: impossible to resolve dependencies:
        resolve failed - see output for details
        at org.apache.ivy.ant.IvyResolve.doExecute(IvyResolve.java:251)
        at org.apache.ivy.ant.IvyTask.execute(IvyTask.java:277)
        at org.apache.ivy.ant.IvyPostResolveTask.ensureResolved(IvyPostResolveTask.java:217)
        at org.apache.ivy.ant.IvyPostResolveTask.prepareAndCheck(IvyPostResolveTask.java:164)
        at org.apache.ivy.ant.IvyRetrieve.doExecute(IvyRetrieve.java:57)
        at org.apache.ivy.ant.IvyTask.execute(IvyTask.java:277)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:390)
        at org.apache.tools.ant.Target.performTasks(Target.java:411)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
        at org.apache.tools.ant.Main.runBuild(Main.java:809)
        at org.apache.tools.ant.Main.startAnt(Main.java:217)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

**Comment by hlinski** [comment]
i have same problem on mac os x:

```
    ---------------------------------------------------------------------
    |                  |            modules            ||   artifacts   |
    |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
    ---------------------------------------------------------------------
    |      default     |   96  |   0   |   0   |   11  ||   85  |   0   |
    ---------------------------------------------------------------------
```

[ivy:retrieve] 
[ivy:retrieve] :: problems summary ::
[ivy:retrieve] :::: WARNINGS
[ivy:retrieve]          ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve]          ::          UNRESOLVED DEPENDENCIES         ::
[ivy:retrieve]          ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve]          :: jline#jline;0.9.94: configuration not found in jline#jline;0.9.94: 'compile'. It was required from org.apache.cassandra#cassandra-all;0.8.4 compile
[ivy:retrieve]          :: javax.servlet#servlet-api;2.5: configuration not found in javax.servlet#servlet-api;2.5: 'compile'. It was required from org.apache.thrift#libthrift;0.6.1 compile
[ivy:retrieve]          ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve] 
[ivy:retrieve] :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS

BUILD FAILED
/opt/local/share/solandra/build.xml:102: impossible to resolve dependencies:
        resolve failed - see output for details

**Comment by mevivs** [comment]
i also faced the same issue. But i cleaned up my .ivy/cache and tried build again.
It was succesfull
