### ISSUE TITLE
Fails to run on Cygwin

### ISSUE THREAD

**Issue by chaostheory** [tjake/Solandra#118]
### Details:

I do not have either CASSANDRA_HOME or CASSANDRA_MAIN set.

I cannot seem to install getopt in Cygwin.
### Problem:

Attempting to run it results in "line 133: getopt: command not found"

**Comment by chaostheory** [comment]
I installed a package called _util-linux_ to fix the getopt problem but now there's a new error:

> $ Exception in thread "main" java.lang.NoClassDefFoundError: solandra/SolandraServer
> Caused by: java.lang.ClassNotFoundException: solandra.SolandraServer
>         at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
> Could not find the main class: solandra.SolandraServer.  Program will exit.

**Comment by tjake** [comment]
This mean's the classpath isn't correct, not seeing the lib dir, I don't have windows can you see if you can patch solandra.bat to work? :)

**Comment by chaostheory** [comment]
I'll try - it's been a while since I used Windows hehe

**Comment by smecsia** [comment]
I had the same problem with solandra under cygwin. But I've patched solandra.bat using the lines below and the problem disappeared.

:append
set "baseFilePath=%1"
call set "baseFilePath=%%baseFilePath:%CASSANDRA_HOME%=..%%"
set CLASSPATH=%CLASSPATH%;%baseFilePath%
goto :eof

**Comment by hodgsonsam** [comment]
Just trying to get Solandra up and running on Debian here and getting the exact same error upon startup, using Cass 1.1.5, tested on ubuntu with Cass 1.1.5 in the same manner and it worked no probs. Any ideas how to set the correct classpath on linux?

Cheers
