### ISSUE TITLE
Checking out  0.7 Solandra gives error during runtime.

### ISSUE THREAD

**Issue by VanitySoft** [tjake/Solandra#132]
after building from ivy(deleting cache too) ...starting up a test i keep getting:  ...what dependency is not satisfied?

java.lang.NoSuchMethodError: org.apache.solr.common.util.DOMUtil.substituteProperties(Lorg/w3c/dom/Node;Ljava/util/Properties;)V
    at org.apache.solr.core.Config.<init>(Config.java:165)
    at org.apache.solr.servlet.SolrDispatchFilter.<init>(SolrDispatchFilter.java:76)
    at solandra.SolandraDispatchFilter.<init>(SolandraDispatchFilter.java:35)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at java.lang.Class.newInstance0(Class.java:355)
    at java.lang.Class.newInstance(Class.java:308)
    at org.mortbay.jetty.servlet.Holder.newInstance(Holder.java:153)
    at org.mortbay.jetty.servlet.FilterHolder.doStart(FilterHolder.java:92)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:713)
    at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
    at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:518)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
    at org.mortbay.jetty.Server.doStart(Server.java:224)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at solandra.JettySolandraRunner.start(JettySolandraRunner.java:109)
    at solandra.JettySolandraRunner.start(JettySolandraRunner.java:103)
    at solandra.SolandraTestRunner$1.run(SolandraTestRunner.java:57)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
 INFO 22:51:58,792 Started SocketConnector@0.0.0.0:8983
 INFO 22:52:18,121 Running tests for core: 187849903262046

**Comment by VanitySoft** [comment]
for some reason this happens within my Eclipse, but solandra starts up ok via command line, so I am closing.
