### ISSUE TITLE
Execution Error when Retrieving 10000 documents

### ISSUE THREAD

**Issue by pcoleman** [tjake/Solandra#136]
When we run a query to retrieve 10,000 or more documents using solrj we receive the following error. We are using the default settings for Solandra. We were hoping you knew what might be causing this:

2011-10-09 17:16:47:351 Error retrieving user: 23
com.df.common.exception.DFCommonException: Error executing query
        at com.df.common.data.solr.SolrDAO.getQueryResult(SolrDAO.java:325)
        at com.df.common.business.QueryFacade.getQueryData(QueryFacade.java:94)
        at com.df.server.query.DatafinitiQuery.doGet(DatafinitiQuery.java:149)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:291)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:602)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
        at java.lang.Thread.run(Thread.java:662)
Caused by: org.apache.solr.client.solrj.SolrServerException: Error executing query
        at org.apache.solr.client.solrj.request.QueryRequest.process(QueryRequest.java:95)
        at org.apache.solr.client.solrj.SolrServer.query(SolrServer.java:118)
        at com.datafiniti.common.data.solr.SolrDAO.getQueryResult(SolrDAO.java:178)
        ... 16 more
Caused by: org.apache.solr.common.SolrException: Form too large245858>200000  java.lang.IllegalStateException: Form too large245858>200000      at org.mortbay.jetty.Request.extractParameters(Request.java:1561)       at org.mortbay.jetty.Request.getParameterMap(Request.java:870)        at org.apache.solr.request.ServletSolrParams.<init>(ServletSolrParams.java:29)  at org.apache.solr.servlet.StandardRequestParser.parseParamsAndFillStreams(SolrRequestParsers.java:394)       at org.apache.solr.servlet.SolrRequestParsers.parse(SolrRequestParsers.java:115)        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:223)     at solandra.SolandraDispatchFilter.doFilter(SolandraDispatchFilter.java:137)  at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)      at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)   at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)     at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)     at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)   at org.mortbay.jetty.Server.handle(Server.java:326)     at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)      at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)   at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)  at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)     at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)   at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)       at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)  Form too large245858>200000  java.lang.IllegalStateException: Form too large245858>200000   at org.mortbay.jetty.Request.extractParameters(Request.java:1561)       at org.mortbay.jetty.Request.getParameterMap(Request.java:870)  at org.apache.solr.request.ServletSolrParams.<init>(ServletSolrParams.java:29)        at org.apache.solr.servlet.StandardRequestParser.parseParamsAndFillStreams(SolrRequestParsers.java:394)         at org.a

Form too large245858>200000  java.lang.IllegalStateException: Form too large245858>200000       at org.mortbay.jetty.Request.extractParameters(Request.java:1561)       at org.mortbay.jetty.Request.getParameterMap(Request.java:870)        at org.apache.solr.request.ServletSolrParams.<init>(ServletSolrParams.java:29)  at org.apache.solr.servlet.StandardRequestParser.parseParamsAndFillStreams(SolrRequestParsers.java:394)         at org.apache.solr.servlet.SolrRequestParsers.parse(SolrRequestParsers.java:115)      at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:223)     at solandra.SolandraDispatchFilter.doFilter(SolandraDispatchFilter.java:137)  at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)      at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)     at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)   at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)     at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)     at org.mortbay.jetty.Server.handle(Server.java:326)   at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)      at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)     at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)     at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)     at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)     at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)  Form too large245858>200000  java.lang.IllegalStateException: Form too large245858>200000   at org.mortbay.jetty.Request.extractParameters(Request.java:1561)       at org.mortbay.jetty.Request.getParameterMap(Request.java:870)  at org.apache.solr.request.ServletSolrParams.<init>(ServletSolrParams.java:29)        at org.apache.solr.servlet.StandardRequestParser.parseParamsAndFillStreams(SolrRequestParsers.java:394)

**Comment by pcoleman** [comment]
Forgot to include this in the first post. In the jetty xml.
maxFormContentSize = 10000000

**Comment by pcoleman** [comment]
Ended up using the -Dorg.mortbay.jetty.Request.maxFormContentSize=10000000 property flag. Fixed the issue
