### ISSUE TITLE
SolrReopenComponent Exception

### ISSUE THREAD

**Issue by snez** [tjake/Solandra#14]
null

java.io.IOException
    at lucandra.IndexReader.document(IndexReader.java:281)
    at org.apache.solr.search.SolrIndexReader.document(SolrIndexReader.java:259)
    at solandra.SolandraReopenComponent.process(SolandraReopenComponent.java:98)
    at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:195)
    at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:131)
    at org.apache.solr.core.SolrCore.execute(SolrCore.java:1316)
    at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:338)
    at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:241)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1089)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:365)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:712)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:405)
    at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:211)
    at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:139)
    at org.mortbay.jetty.Server.handle(Server.java:285)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:502)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:821)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:513)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:208)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:378)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:226)
    at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:442)

How to reproduce:
- Launch 2 instances of cassandra forming a 2 node cluster ring
- Start solandra on both nodes
- ./post.sh something from node A
- query solr for that something from node B (works)
- kill node A's cassandra instance
- repeat the same query from node B (throws an exception) - The data can be retrieved from node B through cassandra, but not through solandra

**Comment by snez** [comment]
Two additional notes on this:
a) If you restart cassandra & solr then you do get the results back without an exception
b) Using the same configuration, if you insert something from node B and try to read it from node A, solr returns numFound = 1 but the doc xml tag is empty

**Comment by tjake** [comment]
There are still some solr caches I need to bypass that could be causing this. I'm going to create my own SearchComponent for this purpose

**Comment by tjake** [comment]
The connections are now more tolerant, could you give it another try?

**Comment by tjake** [comment]
this is fixed

**Comment by snez** [comment]
Amazing
