### ISSUE TITLE
Embedding in cassandra 1.0.6 does not work

### ISSUE THREAD

**Issue by sahlex** [tjake/Solandra#159]
Hi.

If I use the instructions for _"embedding in an existing cassandra distribution"_, starting solandra leads to an error:

<pre>
./solandra -f

 INFO 10:29:37,629 Logging initialized                          
 INFO 10:29:37,681 Sucessfully Hijacked FieldCacheImpl          
 INFO 10:29:37,763 Logging initialized                          
 INFO 10:29:37,767 JVM vendor/version: Java HotSpot(TM) Server VM/1.6.0_23
 ...
 INFO 10:29:42,435 Cassandra version: 1.0.6
 INFO 10:29:42,435 Thrift API version: 19.19.0
 INFO 10:29:42,435 Loading persisted ring state
 INFO 10:29:42,437 Starting up server gossip
 INFO 10:29:42,458 Enqueuing flush of Memtable-LocationInfo@24594643(29/36 serialized/live bytes, 1 ops)
 INFO 10:29:42,460 Writing Memtable-LocationInfo@24594643(29/36 serialized/live bytes, 1 ops)
 INFO 10:29:42,576 Completed flushing /data/cassandra/data/system/LocationInfo-hc-27-Data.db (80 bytes)
 INFO 10:29:42,665 Starting Messaging Service on port 7000
 INFO 10:29:42,744 Using saved token 81895375634557706535325560078039393189
 INFO 10:29:42,747 Enqueuing flush of Memtable-LocationInfo@4349625(53/66 serialized/live bytes, 2 ops)
 INFO 10:29:42,747 Writing Memtable-LocationInfo@4349625(53/66 serialized/live bytes, 2 ops)
 INFO 10:29:42,849 Completed flushing /data/cassandra/data/system/LocationInfo-hc-28-Data.db (163 bytes)
 INFO 10:29:42,852 Node localhost/127.0.0.1 state jump to normal
 INFO 10:29:42,882 Bootstrap/Replace/Move completed! Now serving reads.
 INFO 10:29:42,882 Compacting [SSTableReader(path='/data/cassandra/data/system/LocationInfo-hc-26-Data.db'), SSTableReader(path='/data/cassandra/data/system/LocationInfo-hc-25-Data.db'), SSTableReader(path='/data/cassandra/data/system/LocationInfo-hc-27-Data.db'), SSTableReader(path='/data/cassandra/data/system/LocationInfo-hc-28-Data.db')]
 INFO 10:29:42,884 Will not load MX4J, mx4j-tools.jar is not in the classpath
 INFO 10:29:43,048 Binding thrift service to localhost/127.0.0.1:9160
 INFO 10:29:43,085 Using TFastFramedTransport with a max frame size of 15728640 bytes.
 INFO 10:29:43,091 Using synchronous/threadpool thrift server on localhost/127.0.0.1 : 9160
 INFO 10:29:43,092 Listening for thrift clients...
ERROR 10:29:43,109 Fatal exception in thread Thread[main,5,main]
java.lang.NoSuchMethodError: org.apache.cassandra.config.DatabaseDescriptor.getNonSystemTables()Ljava/util/List;
        at lucandra.CassandraUtils.createCassandraSchema(CassandraUtils.java:310)
        at lucandra.CassandraUtils.startupServer(CassandraUtils.java:283)
        at solandra.SolandraServer.main(SolandraServer.java:39)
 INFO 10:29:43,168 Compacted to [/data/cassandra/data/system/LocationInfo-hc-29-Data.db,].  752 to 346 (~46% of original) bytes for 3 keys at 0,001183MB/s.  Time: 279ms.
</pre>

Regards, 
Alexander.

**Comment by sahlex** [comment]
Used the changes from https://github.com/tjake/Solandra/pull/154.
