### ISSUE TITLE
Solandra Start Error

### ISSUE THREAD

**Issue by dr10** [tjake/Solandra#162]
Hi, 

```
    I'am new to this technology and trying to run Solandra on local VM machine but i'am getting the following error can u help me ..... I have checked with the JAVA version n the JAVA_HOME both but still the error exist .....
```

Exception in thread "main" java.lang.NoClassDefFoundError: solandra/SolandraServer
Caused by: java.lang.ClassNotFoundException: solandra.SolandraServer
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
Could not find the main class: solandra.SolandraServer.  Program will exit.

Waiting for the reply Eagerly.... 

Thanks, 
Regard's,
Hiten Tathe 
+91-9987995056......

**Comment by grandmoffjake** [comment]
For anyone else stumbling on this one - for mine, I had to symlink the build directory in the solandra-app directory

**Comment by denizdurmus87** [comment]
I have experienced the same issue... For me, I just run the solandra from solandra-app folder, without going to bin folder and there is no error.
