### ISSUE TITLE
MoreLikeThis

### ISSUE THREAD

**Issue by hodgsonsam** [tjake/Solandra#181]
Hi,

Seeing the following when trying to use MTL query type, any suggestions are greatly appreciated:

http://localhost:8983/solandra/culture/select?qt=mlt&&mlt.fl=body&q=id:1269312154160926&debugQuery=on

<response>
<lst name="responseHeader">
<int name="status">0</int>
<int name="QTime">2</int>
</lst>
<result name="match" numFound="0" start="0"/>
<null name="response"/>
<str name="exception_during_debug">
java.lang.RuntimeException: java.lang.NullPointerException at org.apache.solr.search.QueryParsing.toString(QueryParsing.java:594) at org.apache.solr.util.SolrPluginUtils.doStandardDebug(SolrPluginUtils.java:416) at org.apache.solr.handler.MoreLikeThisHandler.handleRequestBody(MoreLikeThisHandler.java:201) at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:129) at org.apache.solr.core.SolrCore.execute(SolrCore.java:1368) at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:356) at solandra.SolandraDispatchFilter.execute(SolandraDispatchFilter.java:171) at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:252) at solandra.SolandraDispatchFilter.doFilter(SolandraDispatchFilter.java:137) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212) at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399) at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182) at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766) at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) at org.mortbay.jetty.Server.handle(Server.java:326) at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542) at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928) at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549) at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212) at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228) at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582) Caused by: java.lang.NullPointerException at org.apache.solr.search.QueryParsing.toString(QueryParsing.java:563) at org.apache.solr.search.QueryParsing.toString(QueryParsing.java:591) ... 21 more
</str>
</response>

Cheers

Sam

**Comment by hodgsonsam** [comment]
turning debug mode off prevents the error, think this is probably something im doing in the query as i cant replicate the error on basic queries.

**Comment by hodgsonsam** [comment]
Solr bug:

https://issues.apache.org/jira/browse/SOLR-4290
