### ISSUE TITLE
indexing on the local, and querying from the remote does not work

### ISSUE THREAD

**Issue by eurospy** [tjake/Solandra#20]
When I try to index on the localhost where cassandra instance is running and if I try to search from the remote host, I get an exception like this.

Exception in thread "main" java.lang.RuntimeException: invalid term format: -1 vYJoT????type????0
    at lucandra.CassandraUtils.parseTerm(CassandraUtils.java:159)
    at lucandra.LucandraTermEnum.loadTerms(LucandraTermEnum.java:245)
    at lucandra.LucandraTermEnum.skipTo(LucandraTermEnum.java:89)
    at lucandra.IndexReader.terms(IndexReader.java:390)
    at org.apache.lucene.search.PrefixTermEnum.<init>(PrefixTermEnum.java:41)
    at org.apache.lucene.search.PrefixQuery.getEnum(PrefixQuery.java:45)
    at org.apache.lucene.search.MultiTermQuery$ConstantScoreAutoRewrite.rewrite(MultiTermQuery.java:227)
    at org.apache.lucene.search.MultiTermQuery.rewrite(MultiTermQuery.java:382)
    at org.apache.lucene.search.BooleanQuery.rewrite(BooleanQuery.java:438)
    at org.apache.lucene.search.IndexSearcher.rewrite(IndexSearcher.java:307)
    at org.apache.lucene.search.Query.weight(Query.java:98)
    at org.apache.lucene.search.Searcher.createWeight(Searcher.java:230)
    at org.apache.lucene.search.Searcher.search(Searcher.java:181)
    at LucandraTest.main(LucandraTest.java:78)

**Comment by eurospy** [comment]
the same code works on the local by the way

**Comment by tjake** [comment]
Hmm, do the boxes have the same system Locale setting?

**Comment by tjake** [comment]
I think I've fixed this by ensuring all byte arrays use UTF-8 encoding. you'll need to delete and reload your index

**Comment by eurospy** [comment]
It's fixed with your latest commit, we can close this I think

**Comment by tjake** [comment]
fixed
