### ISSUE TITLE
ArrayIndexOutOfBoundsException when using MoreLikeThis functionality in lucene.

### ISSUE THREAD

**Issue by cjhulen** [tjake/Solandra#28]
I have some test cases that reproduce the problem, but it appears an empty field will screw of the lucandra caching.  notice if I call clearCache() the test code will run correctly.

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2
    at org.apache.lucene.search.TermScorer.score(TermScorer.java:130)
    at org.apache.lucene.search.BooleanScorer$BooleanScorerCollector.collect(BooleanScorer.java:80)
    at org.apache.lucene.search.BooleanScorer.nextDoc(BooleanScorer.java:313)
    at org.apache.lucene.search.BooleanScorer.score(BooleanScorer.java:330)
    at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:207)
    at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:168)
    at org.apache.lucene.search.Searcher.search(Searcher.java:98)
    at org.apache.lucene.search.Searcher.search(Searcher.java:108)
    at ReproduceBug.findSimilarItems(ReproduceBug.java:133)
    at ReproduceBug.main(ReproduceBug.java:99)

**Comment by cjhulen** [comment]
****\* Test code to reproduce bug ****

import java.io.StringReader;
import java.util.ArrayList;

import lucandra.CassandraUtils;
import lucandra.IndexReader;
import lucandra.IndexWriter;

//import java.io.File;
//import org.apache.lucene.index.IndexReader;
//import org.apache.lucene.index.IndexWriter;
//import org.apache.lucene.store.Directory;
//import org.apache.lucene.store.FSDirectory;

import org.apache.lucene.analysis.Analyzer;
import org.apache.lucene.analysis.cjk.CJKAnalyzer;
import org.apache.lucene.document.Document;
import org.apache.lucene.document.Field;
import org.apache.lucene.search.IndexSearcher;
import org.apache.lucene.search.Query;
import org.apache.lucene.search.ScoreDoc;
import org.apache.lucene.search.similar.MoreLikeThis;
import org.apache.lucene.util.Version;

public class ReproduceBug {

```
static ArrayList<TestObj> testRun1 = new ArrayList<TestObj>();
static ArrayList<TestObj> testRun2 = new ArrayList<TestObj>();
static ArrayList<TestObj> testRun3 = new ArrayList<TestObj>();

static {
    TestObj testObj1 = new TestObj();
    testObj1.id = "af52bc87-d721-46f8-8e96-fc1afa11b259";
    testObj1.title = ""; // This is a problem
    testObj1.body = "Term gsm carrier Term Blackberry Term htc Iphones 3 Term Iphones ";        

    TestObj testObj1a = new TestObj();
    testObj1a.id = "af52bc87-d721-46f8-8e96-fc1afa11b259";
    testObj1a.title = "no-op"; // This is a OK
    testObj1a.body = "Term gsm carrier Term Blackberry Term htc Iphones 3 Term Iphones ";

    TestObj testObj1b = new TestObj();
    testObj1b.id = "af52bc87-d721-46f8-8e96-fc1afa11b259";
    testObj1b.title = "the"; // this is problem.  Because of stop words ???
    testObj1b.body = "Term gsm carrier Term Blackberry Term htc Iphones 3 Term Iphones ";

    TestObj testObj2 = new TestObj();
    testObj2.id = "6abd1a3a-4d08-4189-a692-6095bd09c65e";
    testObj2.title = "Term touch screen cell phone ";
    testObj2.body = "Term mobile at&t touch screen iphone clone Term sim Term touch screen cell phone ";

    testRun1.add(testObj1);     
    testRun1.add(testObj2);

    testRun2.add(testObj1a);
    testRun2.add(testObj2);

    testRun3.add(testObj1b);
    testRun3.add(testObj2);
}

public static class TestObj {
    public String id;
    public String title;
    public String body;
}

public static void main(String[] args) throws Exception {

    ArrayList<TestObj> testRun = testRun1;
    //ArrayList<TestObj> testRun = testRun2;
    //ArrayList<TestObj> testRun = testRun3;

    String indexName = "ReproduceBugTest" + System.currentTimeMillis();

    Analyzer analyzer = new CJKAnalyzer(Version.LUCENE_30);
    IndexWriter writer = new IndexWriter(indexName, CassandraUtils.createRobustConnection("127.0.0.1", 9160, false, true));
    IndexReader reader = new IndexReader(indexName, CassandraUtils.createRobustConnection("127.0.0.1", 9160, false, true));
    IndexSearcher searcher = new IndexSearcher(reader);

    // Sanity Check to make sure it works with regular Lucene (part1)
    // Uncomment part1 + part2 below to check with regular lucene
    // File indexFile = new File("itemdata/" + indexName);
    // Directory index = FSDirectory.open(indexFile);
    // IndexWriter writer = new IndexWriter(index, analyzer,
    // IndexWriter.MaxFieldLength.LIMITED);

    for (TestObj tobj : testRun) {
        writer.addDocument(exportAnnotationsToLucene(tobj), analyzer);
    }

    writer.commit();

    // Sanity Check to make sure it works with regular Lucene (part 2)
    // IndexReader reader = IndexReader.open(index);
    // IndexSearcher searcher = new IndexSearcher(index);

    for (TestObj tobj : testRun) {

        ArrayList<String> matches = findSimilarItems(tobj, reader, searcher);

        for (String match : matches) {
            System.out.println(match);
        }

        // ***** Clearing the cache will allow it to run without failures
        // *****
        // reader.clearCache();
    }
}

public static Document exportAnnotationsToLucene(TestObj tobj) {

    Document doc = new Document();
    doc.add(new Field("Title", tobj.title, Field.Store.NO, Field.Index.ANALYZED));
    doc.add(new Field("Body", tobj.body, Field.Store.NO, Field.Index.ANALYZED));
    doc.add(new Field("IdKey", tobj.id, Field.Store.YES, Field.Index.NOT_ANALYZED));
    return doc;
}

public static ArrayList<String> findSimilarItems(TestObj tobj, IndexReader reader, IndexSearcher searcher) throws Exception {

    String contents = tobj.title;
    contents += " " + tobj.body;

    MoreLikeThis mlt = new MoreLikeThis(reader);
    mlt.setFieldNames(new String[] { "Title", "Body" });
    StringReader sr = new StringReader(contents);
    mlt.setMinWordLen(2);
    mlt.setBoost(true);
    mlt.setMinTermFreq(1);
    mlt.setMinDocFreq(1);
    Query q = mlt.like(sr);
    ScoreDoc[] hits = searcher.search(q, 24).scoreDocs;

    ArrayList<String> keys = new ArrayList<String>();
    for (int i = 0; i < hits.length; i++) {
        keys.add(searcher.doc(hits[i].doc).get("IdKey"));
    }

    return keys;
}
```

}

**Comment by tjake** [comment]
Hi,  Lucandra was written with the idea of calling reopen()/clearCache() after each search.  Although it's possible to address this use case so it works. But it's meant to be called as you have it (clearCache())

**Comment by cjhulen** [comment]
ah...thanks
