### ISSUE TITLE
NullPointerException when operating with a nonexistent Cassandra instance

### ISSUE THREAD

**Issue by marianosimone** [tjake/Solandra#33]
If the Cassandra instance that holds the indexes used by Lucandra is down (or it doesn't exist), you get a NullPointerException when performing an operation (index, search, delete), instead of getting an Excception that let's you know what the problem in.

e.g:
java.lang.NullPointerException
        at lucandra.LucandraTermEnum.loadTerms(LucandraTermEnum.java:236)
        at lucandra.LucandraTermEnum.skipTo(LucandraTermEnum.java:88)
        at lucandra.IndexReader.docFreq(IndexReader.java:149)
        at org.apache.lucene.search.IndexSearcher.docFreq(IndexSearcher.java:147)
        at org.apache.lucene.search.Similarity.idfExplain(Similarity.java:765)
        at org.apache.lucene.search.TermQuery$TermWeight.<init>(TermQuery.java:46)
        at org.apache.lucene.search.TermQuery.createWeight(TermQuery.java:146)
        at org.apache.lucene.search.Query.weight(Query.java:99)
        at org.apache.lucene.search.Searcher.createWeight(Searcher.java:230)
        at org.apache.lucene.search.Searcher.search(Searcher.java:181)
        at org.apache.lucene.search.Searcher.search(Searcher.java:191)
        at lucandra.IndexWriter.deleteDocuments(IndexWriter.java:268)

Before that, you may see "WARN  [CassandraProxyClient](main) Connection failed to Cassandra node: host:port" on the logs, but I think the NPE should be replaced with something more robust

**Comment by tjake** [comment]
Hmm, well a unchecked exception probably isn't the best choice. but in this situation what would work for you?

**Comment by marianosimone** [comment]
Right now, I'm using a try/catch block, catching the NullPointerException and rethrowing an exception of a type that I created (with the NPE as cause) adding a description that says that the Cassandra instance MAY be down. Whenever the app fails, at least I know that the problem was generated while using Cassandra (because of the type, without having to take a look at the stacktrace) what the problem may be (from previous experience), and don't get just a NPE.

The problem is not that the exception is unchecked, but that a NPE doesn't represent or give a clue about what might have happened. What do you think?

**Comment by tjake** [comment]
What if I kept retrying the supplied address?  This is how the code works for all other cases (failed node, etc).

**Comment by marianosimone** [comment]
I guess you could retry a couple of times... but eventually, IMHO, you have to give up and throw and exception.

**Comment by tjake** [comment]
Problem is if I make it checked exception then I'd pollute the Lucene API. Perhaps I can embed it in a IOException or CorruptedIndexException?

**Comment by marianosimone** [comment]
If you don't want to add new types, an IOException should be OK (nicer if you add a string with the possible reason).

I would prefer an unchecked exception (something like CouldNotConnectToDatabaseException), but that's personal taste ;)
