### ISSUE TITLE
NumberFormatException in IndexWriter.addDocument

### ISSUE THREAD

**Issue by Laurent-Chavet** [tjake/Solandra#38]
I am trying to deploy Solandra and it starts fine (I can go to admin) but I get an error when I try to insert a doc.
I post the exception in case someone already knows what's going on; I will narrow tomorrow to which field is causing the error and post an update. I don't think the problem is with the doc itself as the same code works fine against a regular solr.

SEVERE: java.lang.NumberFormatException: For input string: "<U+0080>Zàº°"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at org.apache.solr.util.NumberUtils.int2sortableStr(NumberUtils.java:36)
        at org.apache.solr.schema.SortableIntField.toInternal(SortableIntField.java:52)
        at org.apache.solr.schema.FieldType$DefaultAnalyzer$1.incrementToken(FieldType.java:320)
        at lucandra.IndexWriter.addDocument(IndexWriter.java:135)
        at lucandra.IndexWriter.updateDocument(IndexWriter.java:356)
        at solandra.SolandraIndexWriter.addDoc(SolandraIndexWriter.java:133)
        at org.apache.solr.update.processor.RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:61)
        at org.apache.solr.handler.XMLLoader.processUpdate(XMLLoader.java:139)
        at org.apache.solr.handler.XMLLoader.load(XMLLoader.java:69)
        at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:54)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:131)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:1316)
        at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:338)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:241)

**Comment by Laurent-Chavet** [comment]
So here are the minimal repro steps:

Schema:
    <fieldType name="sint" class="solr.SortableIntField" sortMissingLast="true" omitNorms="true"/>
    <field name="id" type="sint" indexed="true" stored="true" required="true" />

Add:

```
curl http://hqsslr01:8080/solr/update?commit=true -H "Content-Type: text/xml" --data-binary  '<add>  <doc><field name="id">3</field> </doc></add>'
```

and get that error:

Sep 10, 2010 11:40:31 AM org.apache.solr.common.SolrException log
SEVERE: java.lang.NumberFormatException: For input string: "<U+0080>^@^C"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at org.apache.solr.util.NumberUtils.int2sortableStr(NumberUtils.java:36)
        at org.apache.solr.schema.SortableIntField.toInternal(SortableIntField.java:52)
        at org.apache.solr.schema.FieldType$DefaultAnalyzer$1.incrementToken(FieldType.java:320)
        at lucandra.IndexWriter.addDocument(IndexWriter.java:135)
        at lucandra.IndexWriter.updateDocument(IndexWriter.java:356)
        at solandra.SolandraIndexWriter.addDoc(SolandraIndexWriter.java:133)
        at org.apache.solr.update.processor.RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:61)
        at org.apache.solr.handler.XMLLoader.processUpdate(XMLLoader.java:139)
        at org.apache.solr.handler.XMLLoader.load(XMLLoader.java:69)
        at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:54)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:131)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:1316)
        at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:338)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:128)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:847)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:583)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:454)
        at java.lang.Thread.run(Unknown Source)

**Comment by Laurent-Chavet** [comment]
Using
    <fieldType name="tint" class="solr.TrieIntField" precisionStep="8" omitNorms="true" positionIncrementGap="0"/>
instead of sint seem to fix the problem; I hope this post can help other with the same issue.
