### ISSUE TITLE
NullPointerException in facet component

### ISSUE THREAD

**Issue by karussell** [tjake/Solandra#51]
This error occurs for queries like this:

```
q=test&facet.date.start=NOW/DAY-6DAYS&facet.date.gap=%2B1DAY&facet.date.end=NOW/DAY%2B1DAY&fq=quality_i:[27+TO+*]&fq=dups_i:[*+TO+0]&fq=crt_b:"false"&f.dest_title_1_s.facet.mincount=1&facet=true&f.dest_title_1_s.facet.limit=12&facet.limit=10&facet.date={!ex%3Ddt}dt&f.tag.facet.mincount=2&wt=javabin&rows=15&version=1&f.tag.facet.limit=20&facet.sort=count&facet.query=dt:[NOW/HOURS-8HOURS+TO+*]&facet.query=dt:[*+TO+NOW/DAY-6DAYS]&facet.query=retw_i:[5+TO+*]&facet.query=retw_i:[20+TO+*]&facet.query=retw_i:[50+TO+*]&facet.query=dups_i:[*+TO+0]&facet.query=dups_i:[1+TO+*]&facet.query=quality_i:[*+TO+26]&facet.query=quality_i:[27+TO+*]&facet.query=url_i:[1+TO+*]&facet.query=url_i:0&start=0&facet.field=lang&facet.field=crt_b&facet.field=dest_title_1_s
```

This occurs only sometimes and only for the first query. I'll investigate if this is related due to the date facet, normal facet or facet query.

```
 ERROR SolrCore:139 - java.lang.NullPointerException
    at org.apache.solr.handler.component.FacetComponent.countFacets(FacetComponent.java:260)
    at org.apache.solr.handler.component.FacetComponent.handleResponses(FacetComponent.java:230)
    at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:290)
    at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:131)
    at org.apache.solr.core.SolrCore.execute(SolrCore.java:1316)
    at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:338)
    at solandra.SolandraDispatchFilter.execute(SolandraDispatchFilter.java:169)
    at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:241)
    at solandra.SolandraDispatchFilter.doFilter(SolandraDispatchFilter.java:133)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1084)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:360)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)   
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:722)   
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:404)      
    at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:206)
    at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:139)
    at org.mortbay.jetty.Server.handle(Server.java:324)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:505)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:828)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:514)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:211)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:380)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:451)
```

**Comment by tjake** [comment]
any info on this?

**Comment by karussell** [comment]
It did not occur after the latest changes ... but maybe some special condition was raised :-/

**Comment by tjake** [comment]
I'll close as I cannot re-produce this
