### ISSUE TITLE
NPE when using explicit commit after delete and write

### ISSUE THREAD

**Issue by tnine** [tjake/Solandra#59]
Hi Jake,
  In running our unit tests we create several small documents.  Most of them don't have analyzed fields, and they're aren't stored.  When saving/querying/deleting rapidly, I'll intermittently get this NPE.

```
INFO [btpool0-4] - [SoS] webapp=/solandra path=/select params={sort=crttime_long_index+desc&fl=docId&start=0&q=email_string_multi_index:user1@test.com+%2Bcrttime_long_index:[*+TO+1284093537200]&isShard=true&wt=javabin&fsv=true&rows=10&version=1} hits=0 status=0 QTime=8 
ERROR [btpool0-1] - java.lang.NullPointerException
    at org.apache.solr.handler.component.QueryComponent.mergeIds(QueryComponent.java:462)
    at org.apache.solr.handler.component.QueryComponent.handleResponses(QueryComponent.java:298)
    at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:290)
    at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:131)
    at org.apache.solr.core.SolrCore.execute(SolrCore.java:1316)
    at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:338)
    at solandra.SolandraDispatchFilter.execute(SolandraDispatchFilter.java:170)
    at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:241)
    at solandra.SolandraDispatchFilter.doFilter(SolandraDispatchFilter.java:134)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1089)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:365)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:712)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:139)
    at org.mortbay.jetty.Server.handle(Server.java:295)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:503)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:827)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:511)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:210)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:379)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:226)
    at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:442)
```

**Comment by tjake** [comment]
Fixed by setting cacheInvalidationInterval = 0

**Comment by tnine** [comment]
Hey Jake.  Shouldn't this work with caches and quick writes and deletes and caching enabled?  We still need to perform modifications rapidly even if the results aren't immediately available for viewing.

**Comment by tjake** [comment]
Good point, the problem here is the terms still exist in the term cache but the docs are no longer available.  I suppose I should delete the docs later on to avoid this.

**Comment by tjake** [comment]
fixed by https://github.com/tjake/Solandra/commit/3b661d2a6e4e947c1dc287fcb1483ee525ad04a5
