### ISSUE TITLE
StackOverflow when writing high volumes of small documents

### ISSUE THREAD

**Issue by tnine** [tjake/Solandra#68]
Hi Jake,
  We're noticing this error during testing.  We're writing multiple small documents with multi fields on them.  The fields themselves aren't that large, phone number and email, and we're only adding about 30 per document.  I notice when we write them rapidly after creating the schema seems to produce this error.

<pre>
[com.spidertracks.aviator:systemservice] Caused by: java.lang.StackOverflowError
[16:12:28]: [com.spidertracks.aviator:systemservice]    at java.io.IOException.<init>(IOException.java:41)
[16:12:28]: [com.spidertracks.aviator:systemservice]    at java.io.InterruptedIOException.<init>(InterruptedIOException.java:45)
[16:12:28]: [com.spidertracks.aviator:systemservice]    at java.net.SocketTimeoutException.<init>(SocketTimeoutException.java:24)
[16:12:28]: [com.spidertracks.aviator:systemservice]    at java.net.SocketInputStream.socketRead0(Native Method)
[16:12:28]: [com.spidertracks.aviator:systemservice]    at java.net.SocketInputStream.read(SocketInputStream.java:129)
[16:12:28]: [com.spidertracks.aviator:systemservice]    at java.io.BufferedInputStream.fill(BufferedInputStream.java:218)
[16:12:28]: [com.spidertracks.aviator:systemservice]    at java.io.BufferedInputStream.read(BufferedInputStream.java:237)
[16:12:28]: [com.spidertracks.aviator:systemservice]    at org.apache.commons.httpclient.HttpConnection.isStale(HttpConnection.java:506)
[16:12:28]: [com.spidertracks.aviator:systemservice]    at org.apache.commons.httpclient.HttpConnection.closeIfStale(HttpConnection.java:431)
[16:12:28]: [com.spidertracks.aviator:systemservice]    at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.closeIfStale(MultiThreadedHttpConnectionManager.java:1313)
[16:12:28]: [com.spidertracks.aviator:systemservice]    at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:382)
[16:12:28]: [com.spidertracks.aviator:systemservice]    at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
[16:12:28]: [com.spidertracks.aviator:systemservice]    at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
[16:12:28]: [com.spidertracks.aviator:systemservice]    at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
[16:12:28]: [com.spidertracks.aviator:systemservice]    at org.apache.solr.client.solrj.impl.CommonsHttpSolrServer.request(CommonsHttpSolrServer.java:427)
[16:12:28]: [com.spidertracks.aviator:systemservice]    at org.apache.solr.client.solrj.impl.CommonsHttpSolrServer.request(CommonsHttpSolrServer.java:244)
[16:12:28]: [com.spidertracks.aviator:systemservice]    at org.apache.solr.client.solrj.request.AbstractUpdateRequest.process(AbstractUpdateRequest.java:105)
[16:12:28]: [com.spidertracks.aviator:systemservice]    at org.apache.solr.client.solrj.SolrServer.commit(SolrServer.java:86)
</pre>

**Comment by tjake** [comment]
This looks like your client side error?

**Comment by tnine** [comment]
Hey Jake,
  This is a client side error, but I always receive it when connecting to a single node in a test context.  It appears to be an issue with starting and stopping the Solandra runtime within the same JVM over multiple integration tests.  I haven't changed anything, but your latest code in combination with 0.7.3 seems to have resolved the issue.  If it occurs again I'll let you know.

**Comment by tjake** [comment]
ok thanks
