### ISSUE TITLE
Exception thrown when trying to do update, select etc. for default index.

### ISSUE THREAD

**Issue by elhigu** [tjake/Solandra#74]
I'm using sunbunt library to access Solandra, when I  try to write or query default index, Solandra throws an exception. 

Problem seems to be that sunburnt adds trailing slash after url and Solandra doesn't like itm when using default index:

http://localhost:8983/solandra/update/

```
HTTP ERROR 500
Problem accessing /solandra/update/. Reason:
    java.io.IOException: invalid index
java.lang.RuntimeException: java.io.IOException: invalid index
    at ...
```

http://localhost:8983/solandra/update seems to work as expected

```
HTTP ERROR 400
Problem accessing /solandra/update. Reason:
    missing content stream
```

**Comment by ozkanpakdil** [comment]
I get invalid index exception when I call
http://localhost:8983/solandra/reuters/admin/ping?wt=javabin&version=2.2

HTTP ERROR 500

Problem accessing /solandra/reuters/admin/ping. Reason:

```
java.io.IOException: invalid index
```

java.lang.RuntimeException: java.io.IOException: invalid index
    at org.apache.solr.core.SolandraCoreContainer.getCore(SolandraCoreContainer.java:101)
    at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:194)
    at solandra.SolandraDispatchFilter.doFilter(SolandraDispatchFilter.java:122)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
    at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
    at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:451)
Caused by: java.io.IOException: invalid index
    at org.apache.solr.core.SolandraCoreContainer.readSchema(SolandraCoreContainer.java:166)
    at org.apache.solr.core.SolandraCoreContainer.getCore(SolandraCoreContainer.java:97)
    ... 19 more

Powered by Jetty://

I hope it helps to solve

**Comment by tjake** [comment]
The admin interface isn't supported yet in Solandra. What specifically do you need it for?

**Comment by ozkanpakdil** [comment]
actually I compiled it and test it under linux. there was no problem like this but when I tried it under AIX 5.3 with IBM jdk I get this kind of errors. I am just trying to make it work. and move our production search system into solandra.

when I run ./2-import-data.sh this comes

GWEB4:/home/BUILD/tmp/tjake-Solandra-c27c46d/reuters-demo # ./2-import-data.sh
./2-import-data.sh[7]: curl:  not found.
Posted schema.xml to http://localhost:8983/solandra/schema/reuters
Loading data to solandra, note: this importer uses a slow xml parser
Exception in thread "main" java.lang.RuntimeException: unable to connect to solr server: http://localhost:8983/solandra/reuters
        at org.apache.solr.solrjs.sgml.reuters.ReutersService.<init>(ReutersService.java:93)
        at org.apache.solr.solrjs.sgml.reuters.ReutersService.main(ReutersService.java:63)
Caused by: org.apache.solr.common.SolrException: java.io.IOException: invalid index  java.lang.RuntimeException: java.io.IOException: invalid index     at org.apache.solr.core.SolandraCoreContainer.getCore(SolandraCoreContainer.java:101)   at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:194)     at solandra.SolandraDispatchFilter.doFilter(SolandraDispatchFilter.java:122)    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)      at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)     at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)  at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)     at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)     at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)        at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)         at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)       at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)     at org.mortbay.jetty.Server.handle(Server.java:326)     at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)      at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)      at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)  at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)     at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)     at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)       at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:451) Caused by: java.io.IOException: invalid index        at org.apache.solr.core.SolandraCoreContainer.readSchema(SolandraCoreContainer.java:166)        at org.apache.solr.core.SolandraCoreContainer.getCore(SolandraCoreContainer.java:97)    ... 19 more

java.io.IOException: invalid index  java.lang.RuntimeException: java.io.IOException: invalid index      at org.apache.solr.core.SolandraCoreContainer.getCore(SolandraCoreContainer.java:101)   at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:194)     at solandra.SolandraDispatchFilter.doFilter(SolandraDispatchFilter.java:122)    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)      at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)     at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)  at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)     at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)     at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)        at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)         at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)       at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)     at org.mortbay.jetty.Server.handle(Server.java:326)     at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)      at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)      at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)  at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)     at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)     at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)       at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:451) Caused by: java.io.IOException: invalid index        at org.apache.solr.core.SolandraCoreContainer.readSchema(SolandraCoreContainer.java:166)        at org.apache.solr.core.SolandraCoreContainer.getCore(SolandraCoreContainer.java:97)    ... 19 more

request: http://localhost:8983/solandra/reuters/admin/ping?wt=javabin&version=2.2
        at org.apache.solr.client.solrj.impl.CommonsHttpSolrServer.request(CommonsHttpSolrServer.java:343)
        at org.apache.solr.client.solrj.impl.CommonsHttpSolrServer.request(CommonsHttpSolrServer.java:183)
        at org.apache.solr.client.solrj.request.SolrPing.process(SolrPing.java:60)
        at org.apache.solr.client.solrj.SolrServer.ping(SolrServer.java:105)
        at org.apache.solr.solrjs.sgml.reuters.ReutersService.<init>(ReutersService.java:91)
        ... 1 more
Data loaded, now open ./website/index.html in your favorite browser!

and at /home/BUILD/tmp/tjake-Solandra-c27c46d/solandra-app/logs/2011_05_06.stderrout.log

10:02:09,021 ERROR SolrDispatchFilter:151 - java.lang.RuntimeException: java.io.IOException: invalid index
        at org.apache.solr.core.SolandraCoreContainer.getCore(SolandraCoreContainer.java:101)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:194)
        at solandra.SolandraDispatchFilter.doFilter(SolandraDispatchFilter.java:122)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
        at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
        at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:451)
Caused by: java.io.IOException: invalid index
        at org.apache.solr.core.SolandraCoreContainer.readSchema(SolandraCoreContainer.java:166)
        at org.apache.solr.core.SolandraCoreContainer.getCore(SolandraCoreContainer.java:97)
        ... 19 more

10:02:23,855 ERROR SolrDispatchFilter:151 - java.lang.RuntimeException: java.io.IOException: invalid index
        at org.apache.solr.core.SolandraCoreContainer.getCore(SolandraCoreContainer.java:101)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:194)
        at solandra.SolandraDispatchFilter.doFilter(SolandraDispatchFilter.java:122)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
        at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
        at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:451)
Caused by: java.io.IOException: invalid index
        at org.apache.solr.core.SolandraCoreContainer.readSchema(SolandraCoreContainer.java:166)
        at org.apache.solr.core.SolandraCoreContainer.getCore(SolandraCoreContainer.java:97)
        ... 19 more

those comes.

**Comment by tjake** [comment]
Looks like you don't have curl installed on that system. if you look at /2-import-data.sh it uses curl to post the reuters schema to solandra

**Comment by ozkanpakdil** [comment]
thanks for the info now it works :)
