### ISSUE TITLE
Backtrace on loading Reuters demo data

### ISSUE THREAD

**Issue by davidstrauss** [tjake/Solandra#82]
I'm getting this with a 100% clean build from master and running the Reuters example scripts.

```
21:02:28,492 ERROR SolrDispatchFilter:151 - java.lang.AssertionError
at org.apache.cassandra.db.ColumnFamily.create(ColumnFamily.java:66)
at org.apache.cassandra.db.ColumnFamily.create(ColumnFamily.java:61)
at org.apache.cassandra.db.RowMutation.add(RowMutation.java:144)
at org.apache.cassandra.db.RowMutation.add(RowMutation.java:152)
at lucandra.CassandraUtils.addMutations(CassandraUtils.java:524)
at lucandra.CassandraUtils.addMutations(CassandraUtils.java:487)
at lucandra.IndexWriter.addDocument(IndexWriter.java:321)
at solandra.SolandraIndexWriter.addDoc(SolandraIndexWriter.java:255)
at org.apache.solr.update.processor.RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:61)
at org.apache.solr.handler.XMLLoader.processUpdate(XMLLoader.java:147)
at org.apache.solr.handler.XMLLoader.load(XMLLoader.java:77)
at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:55)
at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:129)
at org.apache.solr.core.SolrCore.execute(SolrCore.java:1360)
at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:356)
at solandra.SolandraDispatchFilter.execute(SolandraDispatchFilter.java:156)
at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:252)
at solandra.SolandraDispatchFilter.doFilter(SolandraDispatchFilter.java:122)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
at org.mortbay.jetty.Server.handle(Server.java:326)
at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)
at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:451)
```

**Comment by tjake** [comment]
It looks like the core wasn't added somehow?

Do you not have curl installed? If you look at 2-import-data.sh you can see it needs to apply the schema.xml

**Comment by davidstrauss** [comment]
I definitely have curl installed.

**Comment by tjake** [comment]
Are you able to access http://localhost:8983/solandra/schema/reuters ? if you get NOT_FOUND then this the schema wasn't posted. 

If this is the case can you re-try running 2-import-data.sh?

**Comment by davidstrauss** [comment]
After rebuilding everything, I can't reproduce this issue. Closing for now.
