### ISSUE TITLE
Exception when deleting many documents

### ISSUE THREAD

**Issue by derryx** [tjake/Solandra#87]
Hi!

I have a 4 node Solandra cluster. I want to delete a bunch of documents with a query like:
&lt;delete&gt;&lt;query&gt;servicename:StreamServe&lt;/query&gt;&lt;/delete&gt;

There are 6500 documents in the index that match that query.

I get an exception when I try to do this (Stacktrace attached at bottom).

CU
Thomas

15:39:50,701 ERROR SolrCore:151 - org.apache.solr.common.SolrException: 1000  java.lang.ArrayIndexOutOfBoundsException: 1000    at lucandra.IndexWriter.deleteDocuments(IndexWriter.java:369)   at solandra.SolandraIndexWriter.deleteByQuery(SolandraIndexWriter.java:452)  at org.apache.solr.update.processor.RunUpdateProcessor.processDelete(RunUpdateProcessorFactory.java:71)         at org.apache.solr.handler.XMLLoader.processDelete(XMLLoader.java:242)  at org.apache.solr.handler.XMLLoader.processUpdate(XMLLoader.java:188)       at org.apache.solr.handler.XMLLoader.load(XMLLoader.java:77)    at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:55)         at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:129)     at org.apache.solr.core.SolrCore.execute(SolrCore.java:1360)    at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:356)  at solandra.SolandraDispatchFilter.execute(SolandraDispatchFilter.java:156)      at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:252)     at solandra.SolandraDispatchFilter.doFilter(SolandraDispatchFilter.java:122)         at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)      at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)     at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)       at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)     at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)     at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)     at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)         at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)       at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)  at org.mortbay.jetty.Server.handle(Server.java:326)     at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)      at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)  at org.mortbay

1000  java.lang.ArrayIndexOutOfBoundsException: 1000    at lucandra.IndexWriter.deleteDocuments(IndexWriter.java:369)   at solandra.SolandraIndexWriter.deleteByQuery(SolandraIndexWriter.java:452)     at org.apache.solr.update.processor.RunUpdateProcessor.processDelete(RunUpdateProcessorFactory.java:71)      at org.apache.solr.handler.XMLLoader.processDelete(XMLLoader.java:242)  at org.apache.solr.handler.XMLLoader.processUpdate(XMLLoader.java:188)  at org.apache.solr.handler.XMLLoader.load(XMLLoader.java:77)         at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:55)         at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:129)     at org.apache.solr.core.SolrCore.execute(SolrCore.java:1360)    at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:356)      at solandra.SolandraDispatchFilter.execute(SolandraDispatchFilter.java:156)  at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:252)     at solandra.SolandraDispatchFilter.doFilter(SolandraDispatchFilter.java:122)    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)   at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)     at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)  at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)  at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)     at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)        at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)      at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)       at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)     at org.mortbay.jetty.Server.handle(Server.java:326)  at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)      at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)     at org.mortbay

request: http://10.234.224.96:8983/solandra/syslog~0/update?wt=javabin&version=2
        at org.apache.solr.client.solrj.impl.CommonsHttpSolrServer.request(CommonsHttpSolrServer.java:436)
        at org.apache.solr.client.solrj.impl.CommonsHttpSolrServer.request(CommonsHttpSolrServer.java:245)
        at org.apache.solr.client.solrj.request.AbstractUpdateRequest.process(AbstractUpdateRequest.java:105)
        at org.apache.solr.client.solrj.SolrServer.deleteByQuery(SolrServer.java:110)
        at solandra.SolandraIndexWriter.deleteByQuery(SolandraIndexWriter.java:438)
        at org.apache.solr.update.processor.RunUpdateProcessor.processDelete(RunUpdateProcessorFactory.java:71)
        at org.apache.solr.handler.XMLLoader.processDelete(XMLLoader.java:242)
        at org.apache.solr.handler.XMLLoader.processUpdate(XMLLoader.java:188)
        at org.apache.solr.handler.XMLLoader.load(XMLLoader.java:77)
        at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:55)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:129)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:1360)
        at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:356)
        at solandra.SolandraDispatchFilter.execute(SolandraDispatchFilter.java:156)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:252)
        at solandra.SolandraDispatchFilter.doFilter(SolandraDispatchFilter.java:122)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
        at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
        at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:451)

15:39:50,702  INFO SolrCore:1370 - [syslog] webapp=/solandra path=/update params={} status=500 QTime=1074

**Comment by tjake** [comment]
This is fixed by bfbeed5

**Comment by derryx** [comment]
Your change now leads to an OutOfMemoryError.

**Comment by tjake** [comment]
Tried a different approach in d288e02

**Comment by tjake** [comment]
Fixed by moving to a using a collector api. tested with 1M docs.
