### ISSUE TITLE
Searching by only facets causes a backtrace

### ISSUE THREAD

**Issue by davidstrauss** [tjake/Solandra#90]
The query and backtrace:

```
22:20:13,416  INFO SolrCore:1370 - [0da105f0-b41e-4815-b26c-d3d0cb2ada7e-dev] webapp=/solandra path=/select params={facet=true&facet.mincount=1&facet.limit=20&q.alt=(uid:22)&json.nl=map&wt=json&version=1.2&rows=10&fl=id,nid,title,comment_count,type,created,changed,score,path,url,uid,name,teaser&start=0&facet.sort=true&q=&bf=recip(rord(created),4,,)^200.0&facet.field=uid&facet.field=type&facet.field=im_vid_3&facet.field=im_vid_2&facet.field=im_vid_1} status=500 QTime=4 
22:20:13,417 ERROR SolrDispatchFilter:151 - java.lang.NullPointerException
at java.io.StringReader.<init>(StringReader.java:50)
at org.apache.lucene.queryParser.QueryParser.parse(QueryParser.java:203)
at org.apache.solr.search.LuceneQParser.parse(LuceneQParserPlugin.java:80)
at org.apache.solr.search.QParser.getQuery(QParser.java:142)
at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:84)
at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:173)
at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:129)
at org.apache.solr.core.SolrCore.execute(SolrCore.java:1360)
at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:356)
at solandra.SolandraDispatchFilter.execute(SolandraDispatchFilter.java:156)
at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:252)
at solandra.SolandraDispatchFilter.doFilter(SolandraDispatchFilter.java:122)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
at org.mortbay.jetty.Server.handle(Server.java:326)
at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:451)
```

**Comment by tjake** [comment]
Any info on how to reproduce this with the reuters demo?

**Comment by fbrier** [comment]
Did David ever get this resolved?  My integration test has an identical stack trace.  I created a query with one parameter:

```
    SolrQuery query = new SolrQuery();
    query.setParam( "code", "CPRAV" );
    QueryResponse rsp = server.getSolrClient().query( query );
```

I could try and duplicate the problem with the reuters demo if that would be helpful.

**Comment by tjake** [comment]
yes please if you could that would be great

**Comment by tjake** [comment]
turns out this is caused by not specifying a query string

**Comment by davidstrauss** [comment]
@tjake Does that mean we're required to specify one? Normal Solr seems to work fine without one as long as other criteria for the search exist.

**Comment by tjake** [comment]
Hmm... I'll test that.

**Comment by davidstrauss** [comment]
Well, I assume it works because it's how Drupal's Solr module constructs some of its queries.
