### ISSUE TITLE
Sorting by Date-field throws IOException

### ISSUE THREAD

**Issue by derryx** [tjake/Solandra#91]
Hello!

I am running a 4 node Solandra cluster. When I try to get a sorted response (sorting on a timestamp field) I get the exception attached at the end.

This problem appears after some time. Before it works ok (but the sorting is not always OK!).

08:24:21,065  INFO SolrCore:1370 - [syslog] webapp=/solandra path=/select params={sort=timestamp+desc&fl=id&start=0&q=_:_&isShard=true&wt=javabin&fsv=true&rows=10&version=2} status=500 QTime=55 
08:24:21,065 ERROR SolrDispatchFilter:151 - java.io.IOException: Field cache data missing
        at org.apache.lucene.search.LucandraFieldCache.getFieldCacheEntries(LucandraFieldCache.java:849)
        at org.apache.lucene.search.LucandraFieldCache.access$000(LucandraFieldCache.java:36)
        at org.apache.lucene.search.LucandraFieldCache$StringIndexCache.createValue(LucandraFieldCache.java:776)
        at org.apache.lucene.search.LucandraFieldCache$Cache.get(LucandraFieldCache.java:233)
        at org.apache.lucene.search.LucandraFieldCache.getStringIndex(LucandraFieldCache.java:756)
        at org.apache.lucene.search.FieldComparator$StringOrdValComparator.setNextReader(FieldComparator.java:777)
        at org.apache.lucene.search.TopFieldCollector$OneComparatorNonScoringCollector.setNextReader(TopFieldCollector.java:95)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:516)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:313)
        at org.apache.solr.search.SolrIndexSearcher.getDocListNC(SolrIndexSearcher.java:1177)
        at org.apache.solr.search.SolrIndexSearcher.getDocListC(SolrIndexSearcher.java:1065)
        at org.apache.solr.search.SolrIndexSearcher.search(SolrIndexSearcher.java:358)
        at org.apache.solr.handler.component.QueryComponent.process(QueryComponent.java:182)
        at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:194)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:129)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:1360)
        at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:356)
        at solandra.SolandraDispatchFilter.execute(SolandraDispatchFilter.java:156)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:252)
        at solandra.SolandraDispatchFilter.doFilter(SolandraDispatchFilter.java:122)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
        at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
        at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:451)

**Comment by ceocoder** [comment]
@derryx did you recently upgrade solandra version? this commit https://github.com/tjake/Solandra/commit/1afe5e3a26b341386b7d67559a248993ae3563b1 added field cache CF, if you did an in place upgrade of solandra.war with old data files, you can get this error

**Comment by derryx** [comment]
I use the Solandra version from 5th of may. No previous index has existed. We started from scratch.

**Comment by tjake** [comment]
Can you post the schema info about the timestamp field so I can try to reproduce locally?

A workaround would be to comment out this line:

https://github.com/tjake/Solandra/blob/solandra/src/lucandra/CassandraUtils.java#L94

**Comment by derryx** [comment]
Field-type definition:
&lt;fieldType name="date" class="solr.DateField" sortMissingLast="true" omitNorms="true"/&gt;

Field-definition:
&lt;field name="timestamp" type="date" indexed="true" stored="true"/&gt;

**Comment by derryx** [comment]
Commenting out

https://github.com/tjake/Solandra/blob/solandra/src/lucandra/CassandraUtils.java#L94

solved the problem.

**Comment by cwesdorp** [comment]
Using the latest pull I also ran into this problem, in my case the sort was on a long field. It is reproduce-able using the schema from my testcase for the other issue, https://github.com/cwesdorp/solandra-issue81-docs . Add some documents and the fire a query with a sort, e.g. "select?q=_:_&wt=json&indent=on&sort=timestamp desc".

**Comment by tjake** [comment]
thanks, I will use this testcase to figure out whats going on

**Comment by tjake** [comment]
@cwesdorp I wasn't able to reproduce with your scripts... I was able to get the sorted results...

curl 'http://localhost:8983/solandra/thoughtbucket/select?q=_:_&wt=json&indent=on&sort=timestamp%20desc'

**Comment by derryx** [comment]
The sorting worked in the beginning but stopped working after moving more and more data into Solandra.

**Comment by tjake** [comment]
interesting some users have TB of data in here and can't reproduce...  I can try reproducing with the benchmark test how many documents do you have in your index?

**Comment by cwesdorp** [comment]
Just pulled the lasted code compiled and tried again. To reproduce I only need to upload two documents.
- ./upload_schema.sh
- ./upload_doc.sh doc1 doc2 commit
- curl 'http://localhost:8983/solandra/thoughtbucket/select?q=_:_&wt=json&indent=on&sort=timestamp%20asc'

``` plain
21:56:36,302 ERROR SolrCore:151 - org.apache.solr.common.SolrException: Field cache data missing  
java.io.IOException: Field cache data missing     
    at org.apache.lucene.search.LucandraFieldCache.getFieldCacheEntries(LucandraFieldCache.java:849)    
    at org.apache.lucene.search.LucandraFieldCache.access$000(LucandraFieldCache.java:36)   
    at org.apache.lucene.search.LucandraFieldCache$LongCache.createValue(LucandraFieldCache.java:622)   
    at org.apache.lucene.search.LucandraFieldCache$Cache.get(LucandraFieldCache.java:233)   
    at org.apache.lucene.search.LucandraFieldCache.getLongs(LucandraFieldCache.java:594)    
    at org.apache.lucene.search.LucandraFieldCache$LongCache.createValue(LucandraFieldCache.java:613)   
    at org.apache.lucene.search.LucandraFieldCache$Cache.get(LucandraFieldCache.java:233)   
    at org.apache.lucene.search.LucandraFieldCache.getLongs(LucandraFieldCache.java:594)    
    at org.apache.lucene.search.FieldComparator$LongComparator.setNextReader(FieldComparator.java:503)  
    at org.apache.lucene.search.TopFieldCollector$OneComparatorNonScoringCollector.setNextReader(TopFieldCollector.java:95)     
    at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:516)    
    at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:313)    
    at org.apache.solr.search.SolrIndexSearcher.getDocListNC(SolrIndexSearcher.java:1177)   
    at org.apache.solr.search.SolrIndexSearcher.getDocListC(SolrIndexSearcher.java:1065)    
    at org.apache.solr.search.SolrIndexSearcher.search(SolrIndexSearcher.java:358)  
    at org.apache.solr.handler.component.QueryComponent.process(QueryComponent.java:182)    
    at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:194)    
    at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:129)    
    at org.apache.solr.core.SolrCore.execute(SolrCore.java:1360)    
    at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:356)  
    at solandra.SolandraDispatchFilter.execute(SolandraDispatchFilter.java:156)     
    at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:252)     


request: http://127.0.0.1:8983/solandra/thoughtbucket~0/select
    at org.apache.solr.client.solrj.impl.CommonsHttpSolrServer.request(CommonsHttpSolrServer.java:436)
    at org.apache.solr.client.solrj.impl.CommonsHttpSolrServer.request(CommonsHttpSolrServer.java:245)
    at org.apache.solr.handler.component.HttpCommComponent$1.call(SearchHandler.java:421)
    at org.apache.solr.handler.component.HttpCommComponent$1.call(SearchHandler.java:393)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
```

**Comment by tjake** [comment]
Suddenly I can reproduce!  I'll try fixing asap

**Comment by tjake** [comment]
Ok the above fixes it. the issue was caused by the way Solandra identifies which index shards are in use...

**Comment by derryx** [comment]
I can confirm that it works now.

Thank you!

**Comment by cwesdorp** [comment]
My test also runs successful now. Thanks!
