### ISSUE TITLE
java.lang.NoClassDefFoundError: org/xerial/snappy/SnappyException

### ISSUE THREAD

**Issue by blinder** [tjake/Solandra#95]
running the ant build with an existing Cassandra install goes fine. but when executing the solandra startup script, an exception is thrown:

Exception in thread "main" java.lang.NoClassDefFoundError: org/xerial/snappy/SnappyException
    at solandra.CassandraStarter.main(CassandraStarter.java:41)
Caused by: java.lang.ClassNotFoundException: org.xerial.snappy.SnappyException
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
    ... 1 more

Missing jar file it would appear. Perhaps this could be cleaned up in the build task?

**Comment by mevivs** [comment]
It is located in lib folder inside.. looks like lib is missing from classpath?

**Comment by tjake** [comment]
should be fixed
